module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/IJin0HirlyeDAzDd83Tj8B',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/1cac42.jpeg',
    NEWSLETTER_JID: '120363421928238889@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝗦𝗘𝗡𝗨 𝗠𝗗 𝗩5',
    OWNER_NAME: 'CHATUWA',
    OWNER_NUMBER: '94741336839',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> ᑕᕼᗩTᑌᗯᗩ ᙭ᗰᗪ𝗦1V',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbAzEINCHDyfr2jLxM3V',
};
